language: python

services:
  - docker

before_install:
  - sudo pip install awscli

script:
  # We use sudo because the test results in files created by the root user from
  # inside the containers, so we need root access to be able to clean up at
  # the end of the tests.
  - sudo make test

  # In script rather than after_success so that failures building/pushing images will show as red
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]] ; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make push ;
    fi

branches:
  only:
    - master
